title: Blog - Zhengji Li
description: "A test blog for CSSE at Del Norte"
owner_name: Zhengji Li
github_username: xinjiav2
github_repo: "portfolio_2025_zhengji_li" 
baseurl: "/portfolio_2025_zhengji_li"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/xinjiav2"}
    - { platform: x, user_url: "" }
    - { platform: youtube, user_url: "" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/rpg.md
  - navigation/game.md
  - navigation/kasm.md
  - navigation/blog.md
  - navigation/search.md
